// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leader_heartbeat.proto

package com.winry.message;

public final class LeaderHeartbeatProto {
  private LeaderHeartbeatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LeaderHeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderHeartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required float version = 1;</code>
     */
    float getVersion();

    /**
     * <code>optional int32 sessionId = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional int32 sessionId = 2;</code>
     */
    int getSessionId();
  }
  /**
   * Protobuf type {@code LeaderHeartbeat}
   */
  public static final class LeaderHeartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LeaderHeartbeat)
      LeaderHeartbeatOrBuilder {
    // Use LeaderHeartbeat.newBuilder() to construct.
    private LeaderHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderHeartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderHeartbeat defaultInstance;
    public static LeaderHeartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderHeartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderHeartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winry.message.LeaderHeartbeatProto.internal_static_LeaderHeartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winry.message.LeaderHeartbeatProto.internal_static_LeaderHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.class, com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderHeartbeat> PARSER =
        new com.google.protobuf.AbstractParser<LeaderHeartbeat>() {
      public LeaderHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderHeartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LeaderHeartbeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private float version_;
    /**
     * <code>required float version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float version = 1;</code>
     */
    public float getVersion() {
      return version_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private int sessionId_;
    /**
     * <code>optional int32 sessionId = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 sessionId = 2;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    private void initFields() {
      version_ = 0F;
      sessionId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sessionId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sessionId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderHeartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderHeartbeat)
        com.winry.message.LeaderHeartbeatProto.LeaderHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.winry.message.LeaderHeartbeatProto.internal_static_LeaderHeartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.winry.message.LeaderHeartbeatProto.internal_static_LeaderHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.class, com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.Builder.class);
      }

      // Construct using com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.winry.message.LeaderHeartbeatProto.internal_static_LeaderHeartbeat_descriptor;
      }

      public com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat getDefaultInstanceForType() {
        return com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.getDefaultInstance();
      }

      public com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat build() {
        com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat buildPartial() {
        com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat result = new com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat) {
          return mergeFrom((com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat other) {
        if (other == com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.winry.message.LeaderHeartbeatProto.LeaderHeartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float version_ ;
      /**
       * <code>required float version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float version = 1;</code>
       */
      public float getVersion() {
        return version_;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder setVersion(float value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0F;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>optional int32 sessionId = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 sessionId = 2;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional int32 sessionId = 2;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000002;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sessionId = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LeaderHeartbeat)
    }

    static {
      defaultInstance = new LeaderHeartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LeaderHeartbeat)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderHeartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LeaderHeartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026leader_heartbeat.proto\"5\n\017LeaderHeartb" +
      "eat\022\017\n\007version\030\001 \002(\002\022\021\n\tsessionId\030\002 \001(\005B" +
      ")\n\021com.winry.messageB\024LeaderHeartbeatPro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LeaderHeartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeaderHeartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LeaderHeartbeat_descriptor,
        new java.lang.String[] { "Version", "SessionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
