// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_message.proto

package com.winry.message;

public final class RaftMessage {
  private RaftMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required float version = 1;</code>
     */
    float getVersion();

    /**
     * <code>required int32 termId = 2;</code>
     */
    boolean hasTermId();
    /**
     * <code>required int32 termId = 2;</code>
     */
    int getTermId();
  }
  /**
   * Protobuf type {@code VoteRequest}
   */
  public static final class VoteRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VoteRequest)
      VoteRequestOrBuilder {
    // Use VoteRequest.newBuilder() to construct.
    private VoteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VoteRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VoteRequest defaultInstance;
    public static VoteRequest getDefaultInstance() {
      return defaultInstance;
    }

    public VoteRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VoteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              termId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winry.message.RaftMessage.internal_static_VoteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winry.message.RaftMessage.internal_static_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winry.message.RaftMessage.VoteRequest.class, com.winry.message.RaftMessage.VoteRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<VoteRequest> PARSER =
        new com.google.protobuf.AbstractParser<VoteRequest>() {
      public VoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VoteRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private float version_;
    /**
     * <code>required float version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float version = 1;</code>
     */
    public float getVersion() {
      return version_;
    }

    public static final int TERMID_FIELD_NUMBER = 2;
    private int termId_;
    /**
     * <code>required int32 termId = 2;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 termId = 2;</code>
     */
    public int getTermId() {
      return termId_;
    }

    private void initFields() {
      version_ = 0F;
      termId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, termId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, termId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.winry.message.RaftMessage.VoteRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteRequest)
        com.winry.message.RaftMessage.VoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.winry.message.RaftMessage.internal_static_VoteRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.winry.message.RaftMessage.internal_static_VoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.winry.message.RaftMessage.VoteRequest.class, com.winry.message.RaftMessage.VoteRequest.Builder.class);
      }

      // Construct using com.winry.message.RaftMessage.VoteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.winry.message.RaftMessage.internal_static_VoteRequest_descriptor;
      }

      public com.winry.message.RaftMessage.VoteRequest getDefaultInstanceForType() {
        return com.winry.message.RaftMessage.VoteRequest.getDefaultInstance();
      }

      public com.winry.message.RaftMessage.VoteRequest build() {
        com.winry.message.RaftMessage.VoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.winry.message.RaftMessage.VoteRequest buildPartial() {
        com.winry.message.RaftMessage.VoteRequest result = new com.winry.message.RaftMessage.VoteRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.termId_ = termId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.winry.message.RaftMessage.VoteRequest) {
          return mergeFrom((com.winry.message.RaftMessage.VoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.winry.message.RaftMessage.VoteRequest other) {
        if (other == com.winry.message.RaftMessage.VoteRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTermId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.winry.message.RaftMessage.VoteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.winry.message.RaftMessage.VoteRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float version_ ;
      /**
       * <code>required float version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float version = 1;</code>
       */
      public float getVersion() {
        return version_;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder setVersion(float value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0F;
        onChanged();
        return this;
      }

      private int termId_ ;
      /**
       * <code>required int32 termId = 2;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000002;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        termId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VoteRequest)
    }

    static {
      defaultInstance = new VoteRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VoteRequest)
  }

  public interface VoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required float version = 1;</code>
     */
    float getVersion();

    /**
     * <code>required int32 termId = 2;</code>
     */
    boolean hasTermId();
    /**
     * <code>required int32 termId = 2;</code>
     */
    int getTermId();
  }
  /**
   * Protobuf type {@code VoteResponse}
   */
  public static final class VoteResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VoteResponse)
      VoteResponseOrBuilder {
    // Use VoteResponse.newBuilder() to construct.
    private VoteResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VoteResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VoteResponse defaultInstance;
    public static VoteResponse getDefaultInstance() {
      return defaultInstance;
    }

    public VoteResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VoteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              termId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winry.message.RaftMessage.internal_static_VoteResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winry.message.RaftMessage.internal_static_VoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winry.message.RaftMessage.VoteResponse.class, com.winry.message.RaftMessage.VoteResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<VoteResponse> PARSER =
        new com.google.protobuf.AbstractParser<VoteResponse>() {
      public VoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VoteResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private float version_;
    /**
     * <code>required float version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float version = 1;</code>
     */
    public float getVersion() {
      return version_;
    }

    public static final int TERMID_FIELD_NUMBER = 2;
    private int termId_;
    /**
     * <code>required int32 termId = 2;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 termId = 2;</code>
     */
    public int getTermId() {
      return termId_;
    }

    private void initFields() {
      version_ = 0F;
      termId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, termId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, termId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.winry.message.RaftMessage.VoteResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteResponse)
        com.winry.message.RaftMessage.VoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.winry.message.RaftMessage.internal_static_VoteResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.winry.message.RaftMessage.internal_static_VoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.winry.message.RaftMessage.VoteResponse.class, com.winry.message.RaftMessage.VoteResponse.Builder.class);
      }

      // Construct using com.winry.message.RaftMessage.VoteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.winry.message.RaftMessage.internal_static_VoteResponse_descriptor;
      }

      public com.winry.message.RaftMessage.VoteResponse getDefaultInstanceForType() {
        return com.winry.message.RaftMessage.VoteResponse.getDefaultInstance();
      }

      public com.winry.message.RaftMessage.VoteResponse build() {
        com.winry.message.RaftMessage.VoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.winry.message.RaftMessage.VoteResponse buildPartial() {
        com.winry.message.RaftMessage.VoteResponse result = new com.winry.message.RaftMessage.VoteResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.termId_ = termId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.winry.message.RaftMessage.VoteResponse) {
          return mergeFrom((com.winry.message.RaftMessage.VoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.winry.message.RaftMessage.VoteResponse other) {
        if (other == com.winry.message.RaftMessage.VoteResponse.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTermId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.winry.message.RaftMessage.VoteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.winry.message.RaftMessage.VoteResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float version_ ;
      /**
       * <code>required float version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float version = 1;</code>
       */
      public float getVersion() {
        return version_;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder setVersion(float value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0F;
        onChanged();
        return this;
      }

      private int termId_ ;
      /**
       * <code>required int32 termId = 2;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000002;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        termId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VoteResponse)
    }

    static {
      defaultInstance = new VoteResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VoteResponse)
  }

  public interface AppendEntriesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required float version = 1;</code>
     */
    float getVersion();

    /**
     * <code>required int32 termId = 2;</code>
     */
    boolean hasTermId();
    /**
     * <code>required int32 termId = 2;</code>
     */
    int getTermId();

    /**
     * <code>optional string log = 3;</code>
     */
    boolean hasLog();
    /**
     * <code>optional string log = 3;</code>
     */
    java.lang.String getLog();
    /**
     * <code>optional string log = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogBytes();
  }
  /**
   * Protobuf type {@code AppendEntriesRequest}
   */
  public static final class AppendEntriesRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AppendEntriesRequest)
      AppendEntriesRequestOrBuilder {
    // Use AppendEntriesRequest.newBuilder() to construct.
    private AppendEntriesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppendEntriesRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppendEntriesRequest defaultInstance;
    public static AppendEntriesRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AppendEntriesRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              termId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              log_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winry.message.RaftMessage.internal_static_AppendEntriesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winry.message.RaftMessage.internal_static_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winry.message.RaftMessage.AppendEntriesRequest.class, com.winry.message.RaftMessage.AppendEntriesRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AppendEntriesRequest> PARSER =
        new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
      public AppendEntriesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntriesRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private float version_;
    /**
     * <code>required float version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float version = 1;</code>
     */
    public float getVersion() {
      return version_;
    }

    public static final int TERMID_FIELD_NUMBER = 2;
    private int termId_;
    /**
     * <code>required int32 termId = 2;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 termId = 2;</code>
     */
    public int getTermId() {
      return termId_;
    }

    public static final int LOG_FIELD_NUMBER = 3;
    private java.lang.Object log_;
    /**
     * <code>optional string log = 3;</code>
     */
    public boolean hasLog() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string log = 3;</code>
     */
    public java.lang.String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          log_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0F;
      termId_ = 0;
      log_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, termId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLogBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, termId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLogBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.winry.message.RaftMessage.AppendEntriesRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesRequest)
        com.winry.message.RaftMessage.AppendEntriesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.winry.message.RaftMessage.AppendEntriesRequest.class, com.winry.message.RaftMessage.AppendEntriesRequest.Builder.class);
      }

      // Construct using com.winry.message.RaftMessage.AppendEntriesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        log_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesRequest_descriptor;
      }

      public com.winry.message.RaftMessage.AppendEntriesRequest getDefaultInstanceForType() {
        return com.winry.message.RaftMessage.AppendEntriesRequest.getDefaultInstance();
      }

      public com.winry.message.RaftMessage.AppendEntriesRequest build() {
        com.winry.message.RaftMessage.AppendEntriesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.winry.message.RaftMessage.AppendEntriesRequest buildPartial() {
        com.winry.message.RaftMessage.AppendEntriesRequest result = new com.winry.message.RaftMessage.AppendEntriesRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.termId_ = termId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.log_ = log_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.winry.message.RaftMessage.AppendEntriesRequest) {
          return mergeFrom((com.winry.message.RaftMessage.AppendEntriesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.winry.message.RaftMessage.AppendEntriesRequest other) {
        if (other == com.winry.message.RaftMessage.AppendEntriesRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        if (other.hasLog()) {
          bitField0_ |= 0x00000004;
          log_ = other.log_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTermId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.winry.message.RaftMessage.AppendEntriesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.winry.message.RaftMessage.AppendEntriesRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float version_ ;
      /**
       * <code>required float version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float version = 1;</code>
       */
      public float getVersion() {
        return version_;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder setVersion(float value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0F;
        onChanged();
        return this;
      }

      private int termId_ ;
      /**
       * <code>required int32 termId = 2;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000002;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        termId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object log_ = "";
      /**
       * <code>optional string log = 3;</code>
       */
      public boolean hasLog() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public java.lang.String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            log_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogBytes() {
        java.lang.Object ref = log_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          log_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder setLog(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        log_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder clearLog() {
        bitField0_ = (bitField0_ & ~0x00000004);
        log_ = getDefaultInstance().getLog();
        onChanged();
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder setLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        log_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AppendEntriesRequest)
    }

    static {
      defaultInstance = new AppendEntriesRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesRequest)
  }

  public interface AppendEntriesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required float version = 1;</code>
     */
    float getVersion();

    /**
     * <code>required int32 termId = 2;</code>
     */
    boolean hasTermId();
    /**
     * <code>required int32 termId = 2;</code>
     */
    int getTermId();

    /**
     * <code>optional string log = 3;</code>
     */
    boolean hasLog();
    /**
     * <code>optional string log = 3;</code>
     */
    java.lang.String getLog();
    /**
     * <code>optional string log = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogBytes();
  }
  /**
   * Protobuf type {@code AppendEntriesResponse}
   */
  public static final class AppendEntriesResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AppendEntriesResponse)
      AppendEntriesResponseOrBuilder {
    // Use AppendEntriesResponse.newBuilder() to construct.
    private AppendEntriesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppendEntriesResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppendEntriesResponse defaultInstance;
    public static AppendEntriesResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AppendEntriesResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              version_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              termId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              log_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.winry.message.RaftMessage.internal_static_AppendEntriesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.winry.message.RaftMessage.internal_static_AppendEntriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.winry.message.RaftMessage.AppendEntriesResponse.class, com.winry.message.RaftMessage.AppendEntriesResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AppendEntriesResponse> PARSER =
        new com.google.protobuf.AbstractParser<AppendEntriesResponse>() {
      public AppendEntriesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntriesResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private float version_;
    /**
     * <code>required float version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float version = 1;</code>
     */
    public float getVersion() {
      return version_;
    }

    public static final int TERMID_FIELD_NUMBER = 2;
    private int termId_;
    /**
     * <code>required int32 termId = 2;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 termId = 2;</code>
     */
    public int getTermId() {
      return termId_;
    }

    public static final int LOG_FIELD_NUMBER = 3;
    private java.lang.Object log_;
    /**
     * <code>optional string log = 3;</code>
     */
    public boolean hasLog() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string log = 3;</code>
     */
    public java.lang.String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          log_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string log = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0F;
      termId_ = 0;
      log_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, termId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLogBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, termId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLogBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.winry.message.RaftMessage.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.winry.message.RaftMessage.AppendEntriesResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesResponse)
        com.winry.message.RaftMessage.AppendEntriesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.winry.message.RaftMessage.AppendEntriesResponse.class, com.winry.message.RaftMessage.AppendEntriesResponse.Builder.class);
      }

      // Construct using com.winry.message.RaftMessage.AppendEntriesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        log_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.winry.message.RaftMessage.internal_static_AppendEntriesResponse_descriptor;
      }

      public com.winry.message.RaftMessage.AppendEntriesResponse getDefaultInstanceForType() {
        return com.winry.message.RaftMessage.AppendEntriesResponse.getDefaultInstance();
      }

      public com.winry.message.RaftMessage.AppendEntriesResponse build() {
        com.winry.message.RaftMessage.AppendEntriesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.winry.message.RaftMessage.AppendEntriesResponse buildPartial() {
        com.winry.message.RaftMessage.AppendEntriesResponse result = new com.winry.message.RaftMessage.AppendEntriesResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.termId_ = termId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.log_ = log_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.winry.message.RaftMessage.AppendEntriesResponse) {
          return mergeFrom((com.winry.message.RaftMessage.AppendEntriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.winry.message.RaftMessage.AppendEntriesResponse other) {
        if (other == com.winry.message.RaftMessage.AppendEntriesResponse.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        if (other.hasLog()) {
          bitField0_ |= 0x00000004;
          log_ = other.log_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasTermId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.winry.message.RaftMessage.AppendEntriesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.winry.message.RaftMessage.AppendEntriesResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float version_ ;
      /**
       * <code>required float version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float version = 1;</code>
       */
      public float getVersion() {
        return version_;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder setVersion(float value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0F;
        onChanged();
        return this;
      }

      private int termId_ ;
      /**
       * <code>required int32 termId = 2;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000002;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 termId = 2;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        termId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object log_ = "";
      /**
       * <code>optional string log = 3;</code>
       */
      public boolean hasLog() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public java.lang.String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            log_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogBytes() {
        java.lang.Object ref = log_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          log_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder setLog(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        log_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder clearLog() {
        bitField0_ = (bitField0_ & ~0x00000004);
        log_ = getDefaultInstance().getLog();
        onChanged();
        return this;
      }
      /**
       * <code>optional string log = 3;</code>
       */
      public Builder setLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        log_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AppendEntriesResponse)
    }

    static {
      defaultInstance = new AppendEntriesResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VoteResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AppendEntriesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AppendEntriesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022raft_message.proto\".\n\013VoteRequest\022\017\n\007v" +
      "ersion\030\001 \002(\002\022\016\n\006termId\030\002 \002(\005\"/\n\014VoteResp" +
      "onse\022\017\n\007version\030\001 \002(\002\022\016\n\006termId\030\002 \002(\005\"D\n" +
      "\024AppendEntriesRequest\022\017\n\007version\030\001 \002(\002\022\016" +
      "\n\006termId\030\002 \002(\005\022\013\n\003log\030\003 \001(\t\"E\n\025AppendEnt" +
      "riesResponse\022\017\n\007version\030\001 \002(\002\022\016\n\006termId\030" +
      "\002 \002(\005\022\013\n\003log\030\003 \001(\tB\023\n\021com.winry.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VoteRequest_descriptor,
        new java.lang.String[] { "Version", "TermId", });
    internal_static_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VoteResponse_descriptor,
        new java.lang.String[] { "Version", "TermId", });
    internal_static_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "Version", "TermId", "Log", });
    internal_static_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "Version", "TermId", "Log", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
